config/routes.rb
Rails.application.routes.draw do

root to: 'pages#home'
get 'about', to: 'pages#about'
get 'signup', to: 'pages#signup'
get 'medicalfund', to: 'pages#medicalfund'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
end

def about
end

end

def signup 
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
 

<html>
<head>
  <title>Awam</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Bungee|Oswald|Teko" rel="stylesheet"> 
<link href="https://fonts.googleapis.com/css?family=Rajdhani" rel="stylesheet"> 
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<div class="container-fluid">
<nav class="navbar navbar-light bg-light" role="navigation">
  


<!-- Brandname + Logo -->

  <div class ="float-left" >
    
    <%= link_to root_path, class: "big navbar-brand" do %>

      <i class="fa fa-gift"></i>  
      Awam
  
    <%end%>
  </div>
  
  <!-- Brandname + Logo -->
  
  <!-- Dropdown on navbar-brand when screen is a bit small -->
<div class="smallic btn-group" role="group">
    <button type="button" class="small btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
    <i class="fa fa-gift"></i> 
      Awam
      
      <span class="caret"></span>
    </button>
    <ul class="smaldr dropdown-menu">
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="/signup">Sign Up</a></li>
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#">Log In</a></li>
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#">Search</a></li>
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#">Medical</a></li>
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#">Education</a></li>
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#">Emergency</a></li>
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#">Memorial</a></li>
    </ul>
  </div>
<!-- Dropdown on navbar-brand when screen is a bit small -->
  
   <!-- Search bar and dropdown link -->
<form class="navbar-form navbar-left" role="search">
  <div class="form-group">
    <input type="text" class="form-control" placeholder="Search Fundraisers">
  </div>
  
  <div class="btn-group" role="group" aria-label="...">
  <button type="submit" class="dab btn btn-default">Search</button>
  <div class="btn-group" role="group">
    <button type="button" class="bigdr btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Categories
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      
    
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="/medicalfund">Medical</a></li>
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#">Education</a></li>
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#">Emergency</a></li>
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#">Memorial</a></li>
    </ul>
  </div>
  </div>
</form>

  <!-- Search bar and dropdown link -->

  <!-- Log in and sign up buttons -->

<div class="navbar-right btn-group" role="group" aria-label="...">

  <%= link_to about_path do %>

  <button type="button" class="lgnin btn btn-default">Log In</button>

  <%end%>

  <%= link_to signup_path do %>

  <button type="button" class="sgnup btn btn-default">Sign Up</button>
  
  <%end%>
  
  <%= link_to about_path do %>
  
  <button type="button" class="htw btn btn-default">How It Works</button>
  
  <%end%>
  
  


<!-- Log in and sign up buttons -->



</div>
</nav>

</div>


<%= yield %>

<h1 id="icons" class="jumbotron jumbotron-fluid container-fluid text-center" >
    <div id="calendar">
        
    <i id= "lock" class="fa fa-calendar"></i>
       <h6 id= "icon_font">  &nbsp; &nbsp; Support Available 24/7</h6>

    <i id= "lock" class="fa fa-comment"></i>
      <h6 id= "icon_font"> &nbsp; &nbsp; Share your story on social media</h6>

    
    <i id= "lock" class="fa fa-globe"></i>
    <h6 id= "icon_font">&nbsp; &nbsp;Awam is known for its national outreach</h6>
    
    </div>
    
    <div id= "expid">
    <i id= "lock" class="fa fa-expeditedssl"></i> 
    <h6 id= "icon_font"> &nbsp; Guaranteed secure money transfer </h6>

    <i id= "lock" class="fa fa-envira"></i>
    <h6 id= "icon_font"> &nbsp; Leader in fundraising across Pakistan</h6>
 
        <i id= "lock" class="fa fa-laptop"></i>
        <h6 id= "icon_font"> &nbsp; Easily accessible from devices</h6>
</div>
   
</h1>

<!-- Footer -->
<footer class="page-footer font-small blue pt-4">

    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">

      <!-- Grid row -->
      <div class="row">

        <!-- Grid column -->
        <div class="col-md-6 mt-md-0 mt-3">

          <!-- Content -->
          <h5 class="text-uppercase">Footer Content</h5>
          <p>Here you can use rows and columns here to organize your footer content.</p>

        </div>
        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none pb-3">

        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">

            <!-- Links -->
            <h5 class="text-uppercase">Links</h5>

            <ul class="list-unstyled">
              <li>
                <a href="#!">Link 1</a>
              </li>
              <li>
                <a href="#!">Link 2</a>
              </li>
              <li>
                <a href="#!">Link 3</a>
              </li>
              <li>
                <a href="#!">Link 4</a>
              </li>
            </ul>

          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 mb-md-0 mb-3">

            <!-- Links -->
            <h5 class="text-uppercase">Links</h5>

            <ul class="list-unstyled">
              <li>
                <a href="#!">Link 1</a>
              </li>
              <li>
                <a href="#!">Link 2</a>
              </li>
              <li>
                <a href="#!">Link 3</a>
              </li>
              <li>
                <a href="#!">Link 4</a>
              </li>
            </ul>

          </div>
          <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2018 Copyright:
      <a>Omar Ibad</a>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->
</body>

</html>

app/views/pages/about.html.erb
<h1> lmfao </h1>

app/views/pages/home.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- jumbotron -->
<h1 class="homej jumbotron jumbotron-fluid container-fluid text-left" >
      
      <div class="msg">
            Help empower your community by 
            </br>
             starting a fundraiser today.
             </br>
     
      <%= link_to signup_path do %>
          <button type="button" class="btn btn-default">Start A Fundraiser</button>
  
      <%end%>
      </div>
</h1>

<h1 class="smallj text-center"> Help empower your community by starting a fundraiser today</h1>
    <!-- buttons beneath jumbotron -->
<img class="smalli" src="https://images.pexels.com/photos/2128/person-woman-sitting-old.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt ="Woman">

<div id = "catsb" class= "btn-group btn-group-justified text-center" role= "group" aria-label="...">
        
    
    <%= link_to signup_path do %>
        <button type="button" class="srtf btn btn-default">Start A Fundraiser</button>
    <%end%>
    
    <%= link_to about_path do %>
        <button type="button" class="expl btn btn-default">Search Initiatives</button>
    <%end%>
  
</div>
</br>
<!-- Categories -->

<h1 class="cats text-center">
    &nbsp; Categories
</h1>


<div  class="btn-group btn-group-justified text-center" role= "group" aria-label="...">
        
    
    <%= link_to medicalfund_path do %>
    <button type="button" class="med btn btn-default">
        <span class="glyphicon glyphicon-heart"></span>
        <br>
           Medical  
    </button>
    
    <%end%>
    
    <%= link_to about_path do %>
       <button type="button" class="edu btn btn-default">
           <span class="glyphicon glyphicon-book"></span>
            <br>
           Education
        </button>
    <%end%>
  
</div>

<div  class= "btn-group btn-group-justified text-center" role= "group" aria-label="...">
        
    
    <%= link_to about_path do %>

        
        <button type="button" class="eme btn btn-default">
            <span class="glyphicon glyphicon-flash"></span>
            <br>
            Emergency
        </button>
        
    <%end%>
    
    <%= link_to about_path do %>
        <button type="button" class="mem btn btn-default">
            <span class="glyphicon glyphicon-leaf"></span>
            <br>
            Memorial  
        </button>
    <%end%>
  
</div>




<h1 class="cats text-center">
    What Category Is Best Suited For You?
</h1>

<div class="sgn">
    <%= link_to signup_path do %>

        
        <button type="button" class="sgn1 btn btn-default">
            Sign Up For Free
        </button>
        <%end%>
</div>
        

app/views/pages/medicalfund.html.erb
<div id= "medtit" class ="container-fluid">
    <div id ="funddiv">
    <h1 id ="fund_title"> Get help with your medical </h1>
  
    <h1 id= "fund_title"> problems </h1>
   
  </br>
    <h2 id="fund_sub"> With an Awam campaign you can</h2>
 
    <h2 id="fund_sub"> get immediate help </h2>
    </div> 
    <img id="haid"src = "https://images.pexels.com/photos/302083/pexels-photo-302083.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt ="hearding aid"> 
</div>
<h1 id= "fund_title2" class="text-center"> Get help with your medical problems </h1>
<div id ="gass" class="container-fluid" >
    <div>
    <h1 id="gass_head" class="text-center"> Leader in Medical Fundraising </h1>
    
    </div>
    <div id="firstg">
        
        <h2 id="gass_sub1" class="text-center"> 500,000</h2>
       
        <h2 id="gass_sub2" class="text-center">  medicine related campaigns</h2>
    </div>
    
    <div id="secondg">
        
        <h2 id="gass_sub1" class="text-center"> 700+ Million</h2>
       
        <h2 id="gass_sub2" class="text-center"> raised per year</h2>
    </div>
    
    <div id="thirdg">
        
        <h2 id="gass_sub1" class="text-center"> Only 3%</h2>
         
        <h2 id="gass_sub2" class="text-center"> platform fee</h2>
    </div>
    
</div>

<div id="car" >
 <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="https://images.pexels.com/photos/377058/pexels-photo-377058.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt="Chania">
      <div class="carousel-caption">
        <h3>Los Angeles</h3>
        <p>LA is always so much fun!</p>
      </div>
    </div>

    <div class="item">
      <img src="https://images.pexels.com/photos/1312023/pexels-photo-1312023.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt="Chicago">
      <div class="carousel-caption">
        <h3>Chicago</h3>
        <p>Thank you, Chicago!</p>
      </div>
    </div>

    <div class="item">
      <img src="https://images.pexels.com/photos/748780/pexels-photo-748780.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt="New York">
      <div class="carousel-caption">
        <h3>New York</h3>
        <p>We love the Big Apple!</p>
      </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

</div>
<h1 class="cats text-center">
    What Category Is Best Suited For You?
</h1>

<div class="sgn">
    <%= link_to signup_path do %>

        
        <button type="button" class="sgn1 btn btn-default">
            Sign Up For Free
        </button>
        <%end%>
</div>

app/views/pages/signup.html.erb
<div class="bgdiv container-fluid">
<div class="back container-fluid">
    </br>
<h1 id="Title" class="sgnupmsg"> Start a fundraiser today</h1>
</br>
<h2 id="Title" class="sgnupmsg2">Activate your account today</h2>

<h2 id="Title" class="sgnupmsg2">to support locals or start</h2>

<h2 id="Title" class="sgnupmsg2"> your own fundraiser!</h2>

</div>
<div class="lginfrm">
<form>
    <h2 class="sgnupmsg3">Login</h2>
    Email Address: </br>
    <input type="text" name="email"> </br>
    Password: </br>
    <input type="text" name="password"> </br>
    </br>
    <button>Log In</button>
    
</form>
</div>
<div class="sgnupfrm">
<form>
    <h2 class="sgnupmsg3">Sign Up</h2>
    First Name: </br>
    <input type="text" name="firstname"> </br>
    Last Name: </br>
    <input type="text" name="lastname"> </br>
    Email Address: </br>
    <input type="text" name="email"> </br>
    Password: </br>
    <input type="text" name="password"> </br>
    Confirm Password: </br>
    <input type="text" name="password"> </br>
    </br>
        <button>Log In</button>

</form>
</div>


</div>